// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('shuttleApp', ['ui.bootstrap', 'ui.router', 'ngAside', 'shuttleApp.controllers']).config(function($stateProvider) {
    return $stateProvider.state('test', {
      templateUrl: 'templates/views/view_test.html',
      controller: 'TestController',
      url: '/test'
    });
  });

}).call(this);

//# sourceMappingURL=app.js.map
