// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('shuttleApp.directives', []).directive('saMatch', function() {
    return {
      restrict: 'E',
      templateUrl: 'templates/directives/dir_match.html',
      controller: function($scope) {
        $scope.player_list = [
          {
            name: "Anish George",
            parish: "Defence Colony"
          }, {
            name: "Jibin George",
            parish: "Defence Colony"
          }, {
            name: "Vineet Topo",
            parish: "Defence Colony"
          }, {
            name: "Bhaskaran Vijayan",
            parish: "Sunlight Colony"
          }, {
            name: "Arushi someone",
            parish: "Sunlight Colony"
          }, {
            name: "Crazy other chick",
            parish: "Sunlight Colony"
          }, {
            name: "Abhilash Verghese",
            parish: "Okhla"
          }, {
            name: "Stuti crazy",
            parish: "Okhla"
          }
        ];
        return $scope.filtered = function(player) {
          return _.without($scope.player_list, player);
        };
      }
    };
  });

}).call(this);

//# sourceMappingURL=match.js.map
