// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('shuttleApp.services').factory('saEncPass', function() {
    return function(password) {
      return CryptoJS.MD5(password).toString(CryptoJS.enc.Hex);
    };
  });

}).call(this);

//# sourceMappingURL=misc.js.map
