// Generated by CoffeeScript 1.9.3
(function() {
  var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  angular.module('shuttleApp.services').factory('saEncPass', function() {
    return function(password) {
      return CryptoJS.MD5(password).toString(CryptoJS.enc.Hex);
    };
  }).factory('saHttp', function($http) {
    var apiKey;
    apiKey = '';
    return {
      setApiKey: function(key) {
        return apiKey = key;
      },
      get: function(url) {
        var sep;
        if (apiKey) {
          if (indexOf.call(url, '?') >= 0) {
            sep = '&';
          } else {
            sep = '?';
          }
          url += sep + 'api_key=' + apiKey;
        }
        return $http.get(url);
      },
      post: function(url, data) {
        if (apiKey) {
          data.api_key = apiKey;
        }
        return $http.post(url, data);
      }
    };
  });

}).call(this);

//# sourceMappingURL=utilities.js.map
