// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('shuttleApp.controllers').controller('LoginController', function($scope, saHttp, saApiEndpoints, saEncPass, toastr, $state) {
    return $scope.submit = function() {
      var pass;
      pass = saEncPass($scope.auth.password);
      $scope.auth.password = '';
      return saHttp.post(saApiEndpoints.login, {
        username: $scope.auth.username,
        password: pass
      }).success(function(d) {
        if (d.success) {
          $scope.auth.isLoggedIn = true;
          saHttp.setApiKey(d.data);
          $state.go('home.about');
          return toastr.success("Welcome " + $scope.auth.username + ". You are successfully logged in as Administrator");
        } else {
          return toastr.error(d.reason || d.error);
        }
      });
    };
  });

}).call(this);

//# sourceMappingURL=credentials.js.map
