// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('shuttleApp.controllers').controller('HomeViewController', function($scope, $log) {
    return $log.info("Home View Initialized");
  });

}).call(this);

//# sourceMappingURL=home.js.map
