// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('shuttleApp.controllers', []).controller('MainController', function($scope, $aside, $state) {
    $scope.openSideMenu = function() {
      return $aside.open({
        templateUrl: 'templates/modals/modal_side_menu.html',
        placement: 'left',
        size: 'sm'
      });
    };
    $scope.auth = {
      isLoggedIn: true
    };
    return $scope.isState = function(st) {
      return $state.includes(st);
    };
  });

}).call(this);

//# sourceMappingURL=main.js.map
