// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('shuttleApp.controllers', []).controller('MainController', function($scope, $aside) {
    return $scope.sideMenu = function() {
      return $aside.open({
        templateUrl: 'templates/modals/modal_side_menu.html',
        placement: 'left',
        size: 'sm'
      });
    };
  });

}).call(this);

//# sourceMappingURL=main.js.map
