// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('shuttleApp.controllers').controller('TestController', function($scope, $modal, $aside) {
    $scope.openModal = function() {
      return $modal.open({
        templateUrl: 'templates/modals/modal_test.html'
      });
    };
    return $scope.openSide = function() {
      return $aside.open({
        templateUrl: 'templates/modals/modal_test.html',
        placement: 'left',
        size: 'sm'
      });
    };
  });

}).call(this);

//# sourceMappingURL=test.js.map
