// Generated by CoffeeScript 1.9.3
(function() {
  angular.module('shuttleApp.controllers').controller('TestController', function($scope, $modal, $aside, toastr, $log, saApiEndpoints) {
    $scope.openModal = function() {
      return $modal.open({
        templateUrl: 'templates/modals/modal_test.html'
      });
    };
    $scope.openSide = function() {
      return $aside.open({
        templateUrl: 'templates/modals/modal_test.html',
        placement: 'left',
        size: 'sm'
      });
    };
    $scope.toast = function() {
      return toastr.success("Yes, we have done it!!!");
    };
    return $log.debug("Login api: " + saApiEndpoints.login);
  });

}).call(this);

//# sourceMappingURL=test.js.map
